// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TreinoAPI.Data;

#nullable disable

namespace TreinoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831185155_AdicionarAdminTipoUsuario")]
    partial class AdicionarAdminTipoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TreinoAPI.Model.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Diastolica")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Estatura")
                        .HasColumnType("numeric");

                    b.Property<string>("Etnia")
                        .HasColumnType("text");

                    b.Property<int?>("FcRepouso")
                        .HasColumnType("integer");

                    b.Property<int?>("FcReserva")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Femur")
                        .HasColumnType("numeric");

                    b.Property<string>("Genero")
                        .HasColumnType("text");

                    b.Property<decimal?>("Glicose")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Hdl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ldl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Massa")
                        .HasColumnType("numeric");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Sistolica")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Tibia")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Triglicerideos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Umero")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Una")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("TreinoAPI.Model.Anamnese", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Objetivo")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Anamnese");
                });

            modelBuilder.Entity("TreinoAPI.Model.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Altura")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<double?>("PerceltualGordura")
                        .HasColumnType("double precision");

                    b.Property<double?>("Peso")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RealizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("TreinoAPI.Model.CargaExercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Carga")
                        .HasColumnType("double precision");

                    b.Property<string>("Exercicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Repeticoes")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TesteCargaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TesteCargaId");

                    b.ToTable("CargasExercicios");
                });

            modelBuilder.Entity("TreinoAPI.Model.DobraCutanea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Abdominal")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AvaliacaoId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Biceps")
                        .HasColumnType("double precision");

                    b.Property<double?>("CoxaMedia")
                        .HasColumnType("double precision");

                    b.Property<double?>("Iliaca")
                        .HasColumnType("double precision");

                    b.Property<int>("Medida")
                        .HasColumnType("integer");

                    b.Property<double?>("Panturrilha")
                        .HasColumnType("double precision");

                    b.Property<double?>("Subescapular")
                        .HasColumnType("double precision");

                    b.Property<double?>("Supraespinhal")
                        .HasColumnType("double precision");

                    b.Property<double?>("Triceps")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.ToTable("DobrasCutaneas");
                });

            modelBuilder.Entity("TreinoAPI.Model.GrupoMuscular", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GruposMusculares");
                });

            modelBuilder.Entity("TreinoAPI.Model.Perimetro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Abdomen")
                        .HasColumnType("double precision");

                    b.Property<double?>("Antebraco_D")
                        .HasColumnType("double precision");

                    b.Property<double?>("Antebraco_E")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AvaliacaoId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Braco_D")
                        .HasColumnType("double precision");

                    b.Property<double?>("Braco_E")
                        .HasColumnType("double precision");

                    b.Property<double?>("Cintura")
                        .HasColumnType("double precision");

                    b.Property<double?>("Coxa_Med_D")
                        .HasColumnType("double precision");

                    b.Property<double?>("Coxa_Med_E")
                        .HasColumnType("double precision");

                    b.Property<double?>("Coxa_Sup_D")
                        .HasColumnType("double precision");

                    b.Property<double?>("Coxa_Sup_E")
                        .HasColumnType("double precision");

                    b.Property<double?>("Panturrilha_D")
                        .HasColumnType("double precision");

                    b.Property<double?>("Panturrilha_E")
                        .HasColumnType("double precision");

                    b.Property<double?>("Quadril")
                        .HasColumnType("double precision");

                    b.Property<double?>("Torax")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId")
                        .IsUnique();

                    b.ToTable("Perimetros");
                });

            modelBuilder.Entity("TreinoAPI.Model.Periodizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Periodizacoes");
                });

            modelBuilder.Entity("TreinoAPI.Model.PeriodizacaoDia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<Guid>("SemanaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SemanaId");

                    b.ToTable("PeriodizacaoDias");
                });

            modelBuilder.Entity("TreinoAPI.Model.PeriodizacaoSemana", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<Guid>("PeriodizacaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PeriodizacaoId");

                    b.ToTable("PeriodizacaoSemanas");
                });

            modelBuilder.Entity("TreinoAPI.Model.Personal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Personais");
                });

            modelBuilder.Entity("TreinoAPI.Model.PersonalAluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("PersonalId", "AlunoId")
                        .IsUnique();

                    b.ToTable("PersonalAlunos");
                });

            modelBuilder.Entity("TreinoAPI.Model.TesteCarga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RealizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("TestesCarga");
                });

            modelBuilder.Entity("TreinoAPI.Model.Treino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("TreinoAPI.Model.TreinoExercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Carga")
                        .HasColumnType("double precision");

                    b.Property<string>("Exercicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Intervalo")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int?>("Repeticoes")
                        .HasColumnType("integer");

                    b.Property<int?>("RiRMax")
                        .HasColumnType("integer");

                    b.Property<int?>("Series")
                        .HasColumnType("integer");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TreinoId");

                    b.ToTable("TreinosExercicios");
                });

            modelBuilder.Entity("TreinoAPI.Model.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHashed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("usuario_tipo_check", "tipo IN ('PERSONAL', 'ALUNO', 'ADMIN')");
                        });
                });

            modelBuilder.Entity("TreinoAPI.Model.VolumeSemanal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrupoMuscularId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PeriodizacaoSemanaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Series")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrupoMuscularId");

                    b.HasIndex("PeriodizacaoSemanaId");

                    b.ToTable("VolumesSemanais");
                });

            modelBuilder.Entity("TreinoAPI.Model.Aluno", b =>
                {
                    b.HasOne("TreinoAPI.Model.Usuario", "Usuario")
                        .WithOne("Aluno")
                        .HasForeignKey("TreinoAPI.Model.Aluno", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TreinoAPI.Model.Anamnese", b =>
                {
                    b.HasOne("TreinoAPI.Model.Aluno", "Aluno")
                        .WithMany("Anamneses")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TreinoAPI.Model.Avaliacao", b =>
                {
                    b.HasOne("TreinoAPI.Model.Aluno", "Aluno")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TreinoAPI.Model.CargaExercicio", b =>
                {
                    b.HasOne("TreinoAPI.Model.TesteCarga", "TesteCarga")
                        .WithMany("CargasExercicios")
                        .HasForeignKey("TesteCargaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TesteCarga");
                });

            modelBuilder.Entity("TreinoAPI.Model.DobraCutanea", b =>
                {
                    b.HasOne("TreinoAPI.Model.Avaliacao", "Avaliacao")
                        .WithMany("DobrasCutaneas")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("TreinoAPI.Model.Perimetro", b =>
                {
                    b.HasOne("TreinoAPI.Model.Avaliacao", "Avaliacao")
                        .WithOne("Perimetro")
                        .HasForeignKey("TreinoAPI.Model.Perimetro", "AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("TreinoAPI.Model.Periodizacao", b =>
                {
                    b.HasOne("TreinoAPI.Model.Aluno", "Aluno")
                        .WithMany("Periodizacoes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TreinoAPI.Model.PeriodizacaoDia", b =>
                {
                    b.HasOne("TreinoAPI.Model.PeriodizacaoSemana", "Semana")
                        .WithMany("PeriodizacaoDias")
                        .HasForeignKey("SemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semana");
                });

            modelBuilder.Entity("TreinoAPI.Model.PeriodizacaoSemana", b =>
                {
                    b.HasOne("TreinoAPI.Model.Periodizacao", "Periodizacao")
                        .WithMany("PeriodizacaoSemanas")
                        .HasForeignKey("PeriodizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Periodizacao");
                });

            modelBuilder.Entity("TreinoAPI.Model.Personal", b =>
                {
                    b.HasOne("TreinoAPI.Model.Usuario", "Usuario")
                        .WithOne("Personal")
                        .HasForeignKey("TreinoAPI.Model.Personal", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TreinoAPI.Model.PersonalAluno", b =>
                {
                    b.HasOne("TreinoAPI.Model.Aluno", "Aluno")
                        .WithMany("Personais")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreinoAPI.Model.Personal", "Personal")
                        .WithMany("Alunos")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("TreinoAPI.Model.TesteCarga", b =>
                {
                    b.HasOne("TreinoAPI.Model.Aluno", "Aluno")
                        .WithMany("TestesCarga")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TreinoAPI.Model.Treino", b =>
                {
                    b.HasOne("TreinoAPI.Model.Aluno", "Aluno")
                        .WithMany("Treinos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TreinoAPI.Model.TreinoExercicio", b =>
                {
                    b.HasOne("TreinoAPI.Model.Treino", "Treino")
                        .WithMany("TreinoExercicios")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("TreinoAPI.Model.VolumeSemanal", b =>
                {
                    b.HasOne("TreinoAPI.Model.GrupoMuscular", "GrupoMuscular")
                        .WithMany("VolumesSemanais")
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreinoAPI.Model.PeriodizacaoSemana", "PeriodizacaoSemana")
                        .WithMany()
                        .HasForeignKey("PeriodizacaoSemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoMuscular");

                    b.Navigation("PeriodizacaoSemana");
                });

            modelBuilder.Entity("TreinoAPI.Model.Aluno", b =>
                {
                    b.Navigation("Anamneses");

                    b.Navigation("Avaliacoes");

                    b.Navigation("Periodizacoes");

                    b.Navigation("Personais");

                    b.Navigation("TestesCarga");

                    b.Navigation("Treinos");
                });

            modelBuilder.Entity("TreinoAPI.Model.Avaliacao", b =>
                {
                    b.Navigation("DobrasCutaneas");

                    b.Navigation("Perimetro");
                });

            modelBuilder.Entity("TreinoAPI.Model.GrupoMuscular", b =>
                {
                    b.Navigation("VolumesSemanais");
                });

            modelBuilder.Entity("TreinoAPI.Model.Periodizacao", b =>
                {
                    b.Navigation("PeriodizacaoSemanas");
                });

            modelBuilder.Entity("TreinoAPI.Model.PeriodizacaoSemana", b =>
                {
                    b.Navigation("PeriodizacaoDias");
                });

            modelBuilder.Entity("TreinoAPI.Model.Personal", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("TreinoAPI.Model.TesteCarga", b =>
                {
                    b.Navigation("CargasExercicios");
                });

            modelBuilder.Entity("TreinoAPI.Model.Treino", b =>
                {
                    b.Navigation("TreinoExercicios");
                });

            modelBuilder.Entity("TreinoAPI.Model.Usuario", b =>
                {
                    b.Navigation("Aluno");

                    b.Navigation("Personal");
                });
#pragma warning restore 612, 618
        }
    }
}
