// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TreinoAPI.Data;

#nullable disable

namespace TreinoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831024713_PerimetroseDobras")]
    partial class PerimetroseDobras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TreinoAPI.Model.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Diastolica")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Estatura")
                        .HasColumnType("numeric");

                    b.Property<string>("Etnia")
                        .HasColumnType("text");

                    b.Property<int?>("FcRepouso")
                        .HasColumnType("integer");

                    b.Property<int?>("FcReserva")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Femur")
                        .HasColumnType("numeric");

                    b.Property<string>("Genero")
                        .HasColumnType("text");

                    b.Property<decimal?>("Glicose")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Hdl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ldl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Massa")
                        .HasColumnType("numeric");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Sistolica")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Tibia")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Triglicerideos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Umero")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Una")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("TreinoAPI.Model.Anamnese", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Objetivo")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Anamnese");
                });

            modelBuilder.Entity("TreinoAPI.Model.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Altura")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<double?>("PerceltualGordura")
                        .HasColumnType("double precision");

                    b.Property<double?>("Peso")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RealizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("TreinoAPI.Model.DobraCutanea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Abdominal")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AvaliacaoId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Biceps")
                        .HasColumnType("double precision");

                    b.Property<double?>("CoxaMedia")
                        .HasColumnType("double precision");

                    b.Property<double?>("Iliaca")
                        .HasColumnType("double precision");

                    b.Property<int>("Medida")
                        .HasColumnType("integer");

                    b.Property<double?>("Panturrilha")
                        .HasColumnType("double precision");

                    b.Property<double?>("Subescapular")
                        .HasColumnType("double precision");

                    b.Property<double?>("Supraespinhal")
                        .HasColumnType("double precision");

                    b.Property<double?>("Triceps")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.ToTable("DobrasCutaneas");
                });

            modelBuilder.Entity("TreinoAPI.Model.Perimetro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Abdomen")
                        .HasColumnType("double precision");

                    b.Property<double?>("Antebraco_D")
                        .HasColumnType("double precision");

                    b.Property<double?>("Antebraco_E")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AvaliacaoId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Braco_D")
                        .HasColumnType("double precision");

                    b.Property<double?>("Braco_E")
                        .HasColumnType("double precision");

                    b.Property<double?>("Cintura")
                        .HasColumnType("double precision");

                    b.Property<double?>("Coxa_Med_D")
                        .HasColumnType("double precision");

                    b.Property<double?>("Coxa_Med_E")
                        .HasColumnType("double precision");

                    b.Property<double?>("Coxa_Sup_D")
                        .HasColumnType("double precision");

                    b.Property<double?>("Coxa_Sup_E")
                        .HasColumnType("double precision");

                    b.Property<double?>("Panturrilha_D")
                        .HasColumnType("double precision");

                    b.Property<double?>("Panturrilha_E")
                        .HasColumnType("double precision");

                    b.Property<double?>("Quadril")
                        .HasColumnType("double precision");

                    b.Property<double?>("Torax")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId")
                        .IsUnique();

                    b.ToTable("Perimetros");
                });

            modelBuilder.Entity("TreinoAPI.Model.Personal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Personais");
                });

            modelBuilder.Entity("TreinoAPI.Model.PersonalAluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("PersonalId", "AlunoId")
                        .IsUnique();

                    b.ToTable("PersonalAlunos");
                });

            modelBuilder.Entity("TreinoAPI.Model.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHashed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TreinoAPI.Model.Aluno", b =>
                {
                    b.HasOne("TreinoAPI.Model.Usuario", "Usuario")
                        .WithOne("Aluno")
                        .HasForeignKey("TreinoAPI.Model.Aluno", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TreinoAPI.Model.Anamnese", b =>
                {
                    b.HasOne("TreinoAPI.Model.Aluno", "Aluno")
                        .WithMany("Anamneses")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TreinoAPI.Model.Avaliacao", b =>
                {
                    b.HasOne("TreinoAPI.Model.Aluno", "Aluno")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TreinoAPI.Model.DobraCutanea", b =>
                {
                    b.HasOne("TreinoAPI.Model.Avaliacao", "Avaliacao")
                        .WithMany("DobrasCutaneas")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("TreinoAPI.Model.Perimetro", b =>
                {
                    b.HasOne("TreinoAPI.Model.Avaliacao", "Avaliacao")
                        .WithOne("Perimetro")
                        .HasForeignKey("TreinoAPI.Model.Perimetro", "AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("TreinoAPI.Model.Personal", b =>
                {
                    b.HasOne("TreinoAPI.Model.Usuario", "Usuario")
                        .WithOne("Personal")
                        .HasForeignKey("TreinoAPI.Model.Personal", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TreinoAPI.Model.PersonalAluno", b =>
                {
                    b.HasOne("TreinoAPI.Model.Aluno", "Aluno")
                        .WithMany("Personais")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreinoAPI.Model.Personal", "Personal")
                        .WithMany("Alunos")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("TreinoAPI.Model.Aluno", b =>
                {
                    b.Navigation("Anamneses");

                    b.Navigation("Avaliacoes");

                    b.Navigation("Personais");
                });

            modelBuilder.Entity("TreinoAPI.Model.Avaliacao", b =>
                {
                    b.Navigation("DobrasCutaneas");

                    b.Navigation("Perimetro");
                });

            modelBuilder.Entity("TreinoAPI.Model.Personal", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("TreinoAPI.Model.Usuario", b =>
                {
                    b.Navigation("Aluno");

                    b.Navigation("Personal");
                });
#pragma warning restore 612, 618
        }
    }
}
